# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-23 08:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
